version: '3.7'

services:

  rails:
    build:
      context: .
    ports:
      - "3001:3000"
    links:
     - mysql
    env_file:
      - 'variables.env'

  mysql:
    image: percona
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./mysql/connection_limit.cnf:/etc/my.cnf.d/connection_limit.cnf
    env_file:
      - 'variables.env'
